### ISSUE TITLE
短信发送失败

### ISSUE THREAD

**Issue by xiaolingwzuit** [wzunjh/Library#1]
阿里云的sdk项目文件不存在，导致短信发送失败，大佬该如何解决

**Comment by wzunjh** [comment]
SmsUtils文件
ASSkey和密钥设置自己的就行

package com.example.demo.utils;


import com.aliyuncs.DefaultAcsClient;
import com.aliyuncs.IAcsClient;
import com.aliyuncs.dysmsapi.model.v20170525.*;
import com.aliyuncs.exceptions.ClientException;
import com.aliyuncs.exceptions.ServerException;
import com.aliyuncs.profile.DefaultProfile;
import com.google.gson.Gson;


/**
 * @author 27877
 */
public class SmsUtils {

    public static void sendSms(String phone,String code){
        DefaultProfile profile = DefaultProfile.getProfile("cn-hangzhou", "", "");

        IAcsClient client = new DefaultAcsClient(profile);

        SendSmsRequest request = new SendSmsRequest();
        request.setSignName("Wzunjh");
        request.setTemplateCode("SMS_257860840");
        request.setPhoneNumbers(phone);
        request.setTemplateParam("{\"code\":\""+code+"\"}");


        System.out.println("阿里云短信服务response信息:");

        try {
            SendSmsResponse response = client.getAcsResponse(request);
            System.out.println(new Gson().toJson(response));
        } catch (ServerException e) {
            e.printStackTrace();
        } catch (ClientException e) {
            System.out.println("ErrCode:" + e.getErrCode());
            System.out.println("ErrMsg:" + e.getErrMsg());
            System.out.println("RequestId:" + e.getRequestId());
        }

    }


}

**Comment by wzunjh** [comment]
谢谢你的提问

**Comment by small02** [comment]
为什么前端启动不了
